#!/bin/bash

#To use this, copy it into your .bashrc and either source .bashrc or restart the terminal.

#This thing is probably not elegant, but it functions.

#If you don't like the colors: -vCO is the directory color, -vC1 is the normal color, -vC2 is the color of executable files and -vC3 is the color of symlinks. Codes are easy to find online. If you don't know how to change them, you honestly shouldn't be playing with your .bashrc!

#Good Luck!
printPretty() 
{ 
    stat -c$'%F\n%n' * | \
    awk -vC0='\033[34m\033[1m' \
        -vC1='\033[0m' \
        -vC2='\033[32m\033[1m' \
        -vC3='\033[36m\033[1m' \
        '/^directory/ \
        {getline LEFT[++DC]; next} \
        {getline RIGHT[++FC]} \
        {for (i=1; i<=FC; i++) \
            {if (system("[ -h \"" RIGHT[i] "\" ]") == 0) \
                RIGHT[i]=C3 RIGHT[i]; \
            if (system("[ -x \"" RIGHT[i] "\" ]") == 0) \
                RIGHT[i]=C2 RIGHT[i]\
            }\
        } END \
        {for (i=1; i<=(DC>FC?DC:FC); i++) \
            printf "%-50s%s\n", C0 LEFT[i], C1 RIGHT[i]\
        }'
}

alias l='printPretty'
